# Site
repository: SJHawa/SJHawa.github.io

# Content configuration version
version: 2

# Personal info
name: 쩡하
title: Flutter & Spring Boot 기반 AI 교육 플랫폼 개발자
email: wkdghk35680@gmail.com
phone: "010-0000-0000"
website: https://SJHawa.github.io

# Dark Mode 설정
darkmode: false

# Social links
github_username: SJHawa
linkedin_username: your-linkedin-id (← 있으면 적고, 없으면 지워도 됨)
notion_username: your-notion (← 링크로 넣을 수 있음)

# Additional icon links
additional_links:
  - title: Notion 포트폴리오
    icon: fab fa-notion
    url: https://www.notion.so/1d7f0def2894804f97cac78c3f273123?pvs=4
  - title: GitHub
    icon: fab fa-github
    url: https://github.com/SJHawa

# About Section
about_profile_image: images/profile.jpg # 있으면 여기에 이미지 경로 넣어줘
about_content: |
  **안녕하세요, 쩡하입니다.**  
  컴퓨터 소프트웨어를 전공하며, 사용자 중심의 기술 구현을 추구하는 개발자입니다.  
  특히 아동 대상 AI 한국어 교육 플랫폼 개발 경험을 통해 Flutter, Spring Boot, AI API 연동, 데이터베이스 설계 등을 실무 수준으로 경험했습니다.

  다양한 협업 환경에서도 적극적으로 소통하며, 사용자의 입장에서 기능을 고민하는 개발자가 되겠습니다.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: 시나브로 (Sinabro)
        link: https://SJHawa.github.io
        link_text: 웹 이력서 보기
        additional_links:
          - title: GitHub Repo
            icon: fab fa-github
            url: https://github.com/SJHawa/sinabro
        quote: >
          AI 기반 한국어 학습 플랫폼 (졸업작품)
        description: |
          Flutter와 Spring Boot를 활용한 아동 대상 교육 앱  
          - 손글씨 인식 받아쓰기 게임 (Google ML Kit, Selvy Pen SDK)  
          - TTS 기반 듣기 게임 / AI 이미지 생성 학습  
          - 부모용 학습 리포트 및 시간 제한 설정 기능

  - title: Experience
    layout: list
    content:
      - layout: right
        title: 동양미래대학교
        sub_title: 컴퓨터소프트웨어학과 학생
        caption: 2022.03 - 현재
        description: |
          팀 프로젝트 중심 수업에서 백엔드와 앱 개발을 병행하며 프로젝트 수행  
          졸업작품으로 AI 기반 Flutter 앱 + Spring Boot 백엔드 시스템 개발

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: 동양미래대학교
        sub_title: 컴퓨터소프트웨어학과
        caption: 2022 - 2025 (예정)
        description: |
          소프트웨어 기초 이론부터 실무 중심 프로젝트 개발 수업 수강  
          Spring Framework, Android, 데이터베이스, Flutter 등 다양한 개발 환경 경험

  - title: Skills & Interests
    layout: text
    content: |
      - Flutter, Dart, Java, Spring Boot
      - MySQL, Firebase, AWS RDS
      - Git, GitHub 협업
      - AI 활용: GPT, DALL·E, Whisper 등
      - 사용자 중심 UI/UX 설계 관심

# Footer
footer_show_references: true

# Theme 설정
remote_theme: sproogen/modern-resume-theme

# Build settings
sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
